version: "3.8"

networks:
  sister:
    name: sister

# volumes:
#   mysqldata:

services:

  vmg:
    # 172.27.0.30:62xx
    image: nginx:1.21-alpine
    # ports:
    #   - "16220:80"
    expose:
      - "80"
    volumes:
      # - ./docker/nginx_listoa/nginxmain.conf:/etc/nginx/nginx.conf
      # - ./docker/nginx_listoa/default.conf:/etc/nginx/conf.d/default.conf
      - ./vmark616g/dist:/usr/share/nginx/html
    restart: always
    networks:
      - sister
    environment:
      -     VIRTUAL_HOST=mark616g.198.23.238.244.nip.io
      - LETSENCRYPT_HOST=mark616g.198.23.238.244.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
      - VIRTUAL_NETWORK=sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "9"