# Generated by Django 3.2 on 2021-09-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_application_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='application',
            name='pts_topology',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
    ]
