# Generated by Django 3.2 on 2021-12-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3430)),
                ('description', models.TextField(max_length=32100)),
                ('url', models.TextField(max_length=30100)),
                ('bhash', models.CharField(max_length=230)),
                ('comment', models.TextField(max_length=31200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
