#!/usr/bin/env bash
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
function Purpose() {
# begin block comment =============================
: <<'END'


#  Purpose:  tar the dkr617 folder - all files. with sudo


# usage:   bash /ap/dkr/dkrcollection617a/tarfull617


END
# end block comment ===============================
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#cd ; 
date ; set +vx  ; set -vx ; # echo off, then echo on
#
dts=$(date +"__%Y.%m.%d_%H.%M.%S")


date

set +vx

cd /ap/dkr
sudo tar -czf dkr617-fullsudo-racknerd_$(date +"_%Y.%m.%d_%H.%M.%S").tgz dkrcollection617a/

date
