#!/usr/bin/env bash
date1=$(date +"__%Y.%m.%d_%H.%M.%S"); echo $date1

# build

cd /ap/dkr/dkrcollection617a
cd ./bmark616h-yard/vuemarks616/vmark616g
source  shb.sh




# notes

notes01() {

docker-compose -f ./bmark616h-yard/php605m/docker-compose.yml     up -d dbm 

docker-compose -f ./bmark616h-yard/dj616b/docker-compose.prod.yml up -d djprod 

docker-compose -f ./bmark616h-yard/vuemarks616/docker-compose.yml up -d vmg


# dev
docker-compose -f ./bmark616h-yard/php605m/docker-compose.yml     up -d adminer php

docker-compose -f ./bmark616h-yard/dj616b/docker-compose.yml      up -d 

cd /ap/dkr/dkrcollection617a
cd ./bmark616h-yard/vuemarks616/vmark616g
bash shdev.sh

}

echo
echo '--- :) --- finished. reached end.'
echo
