version: "3.6"

services:

  djdev:
    # http://10.4.1.231:6461/
    build: ./djangosite
    restart: on-failure
    working_dir: /code
    # set user to root, group to www-data. All files should be delete-able by www-data group.
    # problem is that they are read only for group www-data. Use make perm to make them writable.
    #user: "0:33"
    #user: "1000:1000"
    env_file:
      - ./.env
    entrypoint: /code/entrypoint.sh  
    #
    #  to avoid running apscheduler twice use --noreload   https://stackoverflow.com/questions/33814615/how-to-avoid-appconfig-ready-method-running-twice-in-django
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    #
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./djangosite:/code
      - ../data/djangosite:/data
      # use pip cache to reduce startup time..
      # https://stackoverflow.com/questions/25305788/how-to-avoid-reinstalling-packages-when-building-docker-image-for-python-project
      - ~/sysdata/python-dot-cache/pip/:/root/.cache/pip
    ports:
      - "6461:8000"
    networks:
      - 499d-django_default      




  adminerd:
    # http://10.4.1.231:14123/
    # image: adminer:4.7
    # image: dockette/adminer:full
    image: dgleba/adminer-sqlite:one
    # build: ./adminer-sqlite
    restart: always
    ports:
      - 14123:80
      # 8080 for regular adminer, 80 for dockette
    volumes:
      - ./djangosite/db.sqlite3:/db.sq3
      - ./adminer-sqlite:/var/www/html
    environment:
      - ADMINER_DEFAULT_SERVER=srvr
      - DB_PATH=/db.sq3
      - DB_USER=user
      - DB_PASS=apass
      # - ADMINER_PLUGINS='tables-filter'


# for redis, see django-select2 example.. https://github.com/codingjoe/django-select2/tree/master/example
      # and  https://github.com/wildfish/wildfish-django-starter/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/dev-docker-compose.yml.default



networks:
  499d-django_default:
    name: 499d-django_default

    #  
      #
        #   depends_on:
        #     - db
        # db:
        #   image: "postgres:10.3-alpine"
        #   restart: unless-stopped
        #   env_file:
        #     - ./.env
        #   ports:
        #     - "5432:5432"
        #   volumes:
        #     - ./postgres/data:/var/lib/postgresql/data
        


