# Generated by Django 3.2 on 2021-12-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark616', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmk',
            name='bhash',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='bookmk',
            name='comment',
            field=models.TextField(blank=True, max_length=31200, null=True),
        ),
        migrations.AlterField(
            model_name='bookmk',
            name='description',
            field=models.TextField(blank=True, max_length=32100, null=True),
        ),
        migrations.AlterField(
            model_name='bookmk',
            name='title',
            field=models.CharField(blank=True, max_length=3430, null=True),
        ),
        migrations.AlterField(
            model_name='bookmk',
            name='url',
            field=models.TextField(blank=True, max_length=30100, null=True),
        ),
    ]
