# Generated by Django 3.2 on 2022-01-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark616', '0002_auto_20211229_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmk',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='bookmk',
            name='body',
            field=models.TextField(blank=True, max_length=32100, null=True),
        ),
    ]
