# Generated by Django 3.2 on 2022-01-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark616', '0003_auto_20220107_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmk',
            name='bhash',
            field=models.CharField(blank=True, max_length=1930, null=True),
        ),
        migrations.AlterField(
            model_name='bookmk',
            name='title',
            field=models.CharField(blank=True, max_length=6430, null=True),
        ),
    ]
