# Generated by Django 3.2 on 2022-01-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark616', '0004_auto_20220107_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmk',
            name='tagtext',
            field=models.CharField(blank=True, max_length=1930, null=True),
        ),
    ]
