# Generated by Django 3.2 on 2022-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark616', '0005_bookmk_tagtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmk',
            name='is_shaarli',
            field=models.IntegerField(null=True),
        ),
    ]
