# Generated by Django 3.2 on 2022-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark616', '0008_alter_bookmk_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmk',
            name='id_shaarli',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
