# Generated by Django 3.2 on 2021-08-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_group_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
