# Generated by Django 3.2 on 2021-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='application',
            name='vehicles',
            field=models.ManyToManyField(to='ptsapp.Vehicle'),
        ),
    ]
