# Generated by Django 3.2 on 2021-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0003_auto_20210929_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_identification',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_identification',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='application',
            name='application',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='application',
            name='pts_topology',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_maker',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, default='', max_length=252),
        ),
    ]
