# Generated by Django 3.2 on 2021-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0011_rename_stages_stage_gears'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(blank=True, default='', max_length=252)),
                ('treatment_type', models.CharField(blank=True, default='', max_length=252)),
                ('material_type', models.CharField(blank=True, default='', max_length=252)),
                ('surface_hardness', models.CharField(blank=True, default='', max_length=252)),
                ('surface_hardness_unit', models.CharField(blank=True, default='', max_length=252)),
                ('core_hardness', models.CharField(blank=True, default='', max_length=252)),
                ('core_hardness_unit', models.CharField(blank=True, default='', max_length=252)),
                ('hardness_depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('tensile_strength_N_per_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('yield_point_N_per_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('youngs_modulus_N_per_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('poissons_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('density_kg_per_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('coefficient_of_therma_expansion_10e_6_per_c', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('specific_heat_capacity_J_per_kg_k', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('specific_heat_conductivity_W_per_m_K', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('endurance_limit_root_N_per_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('endurance_limit_flank_N_per_mm3', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('quality_iso_6336_5', models.CharField(blank=True, default='', max_length=252)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(blank=True, default=50, null=True)),
                ('active_status', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gear',
            name='materials',
            field=models.ManyToManyField(to='ptsapp.Material'),
        ),
    ]
