# Generated by Django 3.2 on 2021-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0014_load_spectrum_load_spectrum_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='normal_pressure_angle_deg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
    ]
