# Generated by Django 3.2 on 2021-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0017_alter_gear_root_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='root_diameter',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
    ]
