# Generated by Django 3.2 on 2021-10-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0010_auto_20211020_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='stages',
            new_name='gears',
        ),
    ]
