# Generated by Django 3.2 on 2021-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0015_alter_gear_normal_pressure_angle_deg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='gear_tip_dia_mm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='root_diameter',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
    ]
