# Generated by Django 3.2 on 2021-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0016_auto_20211207_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='root_diameter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
    ]
