# Generated by Django 3.2 on 2021-12-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_application2_vehicle2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle2',
            old_name='Application2s',
            new_name='application2s',
        ),
    ]
