# Generated by Django 3.2 on 2021-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0007_auto_20210930_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_identification',
            field=models.CharField(blank=True, default='', max_length=252, null=True),
        ),
    ]
