# Generated by Django 3.2 on 2021-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0013_auto_20211020_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_spectrum',
            name='load_spectrum_identification',
            field=models.CharField(blank=True, default='', max_length=252, null=True),
        ),
    ]
