version: "3.7"

networks:
  sister:
    name: sister

# volumes:
#   mysqldata:

services:

  vv:
    # 172.27.0.30:62xx
    # image: node:16-alpine
    user: "1000:33"
    working_dir:  /code2

    build: .
    # ports:
    #   - "16220:80"
    expose:
      - "80"
    volumes:
      # - ./docker/nginx_616g/nginxmain.conf:/etc/nginx/nginx.conf
      # - ./docker/nginx_616g/default.conf:/etc/nginx/conf.d/default.conf
      - ./code2:/code2
    restart: always
    networks:
      - sister
    environment:
      # -     VIRTUAL_HOST=mark616g.198.23.238.244.nip.io
      # - LETSENCRYPT_HOST=mark616g.198.23.238.244.nip.io
      # - VIRTUAL_PORT=80
      # - LETSENCRYPT_EMAIL=dgleba@gmail.com
      - VIRTUAL_NETWORK=sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "9"
        