version: '3'

networks:
  sister:
    name: sister

services:
  dbh:
    image: postgres:13.4-alpine
    environment:
      - PQ=he
    env_file:
      - ./.env
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    networks:
      - sister 
  apph:
   # https://hedgep.198.144.183.160.nip.io
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.9.6
    volumes:
      - uploads:/hedgedoc/public/uploads
    env_file:
      - ./.env
    ports:
      - "12121:3000"
    restart: always
    depends_on:
      - dbh
    environment:
      - VIRTUAL_HOST=hedgep.198.144.183.160.nip.io
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=hedgep.198.144.183.160.nip.io
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
    networks:
      - sister 


volumes:
  database:
  uploads:
  