version: "3.6"

networks:
  499d-django_default:
    name: 499d-django_default
  djnet:
    driver: bridge
  sister:
    name: sister
  sister2:
    name: sister2
    
volumes:
  mysqldata:

services:

  djprod:
    # http://192.168.88.60:6464/adminb/blogapp/post/
    build: ./djangosite
    restart: on-failure
    env_file:
      - ./.env
    command: gunicorn --bind 0.0.0.0:8080 --preload  --access-logfile -  --error-logfile -  djangoproj.wsgi 
    expose:
      - "8080"
    depends_on:
      - nginx
    working_dir: /code
    # set user to root, group to www-data. All files should be delete-able by www-data group.
    user: "0:33"
    volumes:
      - ./djangosite:/code
      - ../data/djangosite:/data
      #- ./mediafiles:/code/media
      # use pip cache to reduce startup time..
      # https://stackoverflow.com/questions/25305788/how-to-avoid-reinstalling-packages-when-building-docker-image-for-python-project
      - ~/sysdata/python-dot-cache/pip/:/root/.cache/pip
    networks:
      - 499d-django_default 
      - sister
      - sister2

  # nginx to serve production django
  nginx:
    image: "nginx:1.19-alpine"
    restart: always
    working_dir: /code
    volumes:
      - ./djangosite:/code
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./static:/code/static
      #- ./mediafiles:/code/media
    ports:
      - "6464:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=mark.daveg.win
      - LETSENCRYPT_HOST=mark.davegg.com
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
      # - VIRTUAL_HOST=mark616.198.144.183.160.nip.io,mark.davegg.com,mark.daveg.win
      # - LETSENCRYPT_HOST=mark616.198.144.183.160.nip.io,mark.daveg.win,mark.davegg.com
    networks:
      - 499d-django_default 
      - sister
      - sister2

  # markv:
    # just nginx without vue build 
    # https://mark616vu.198.144.183.160.nip.io/
    # image: "nginx:1.21-alpine"
    # volumes:
      # - ./vue616c:/usr/share/nginx/html
    # expose:
      # - "80"
    # environment:
      # - VIRTUAL_PORT=80
      # - VIRTUAL_HOST=mark616vu.198.144.183.160.nip.io
      # - LETSENCRYPT_HOST=mark616vu.198.144.183.160.nip.io
      # - LETSENCRYPT_EMAIL=dgleba@gmail.com
    # restart: always
    # networks:
      # - sister




  # db:
  #   image: mysql:5.7
  #   restart: always
  #   env_file:
  #     - .env
  #   # environment:
  #   # MYSQL_DATABASE: test
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - "6466:3306"
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #     # - ../sysdata/mysqldata:/var/lib/mysql
  #     # below is old. use the one above this line.
  #     #  use PWD in mysql files volume so each project folder has it's own database folder. This is for mistake proofing. https://github.com/docker/compose/issues/2636
  #     #  I tried directory with no full path.. ERROR: Invalid interpolation format for "volumes" option in service "db": "../datasys/mysql-${PWD##*/}:/var/lib/mysql/"
  #     # - ../datasys/mysql${PWD}:/var/lib/mysql/ # folder for mysql's internal data files.
  #     # folder for scripts, etc.
  #     - ./script:/script 
  #     # folder for exported data, etc.
  #     - ../data/dbhome:/home 
  #   #
  #   # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100k"
  #       max-file: "2"
  #   networks:
  #     - 499d-django_default      


  # adminer:
  #   # http://192.168.88.60:6463
  #   # 10.4.1.231:6117/  use db or 10.4.1.228:3308 for server while logging in.
  #   image: adminer:4.7
  #   restart: always
  #   ports:
  #     - 6463:8080
  #   networks:
  #     - 499d-django_default      

#
#   depends_on:
#     - db
# db:
#   image: "postgres:10.3-alpine"
#   restart: unless-stopped
#   env_file:
#     - ./.env
#   ports:
#     - "5432:5432"
#   volumes:
#     - ./postgres/data:/var/lib/postgresql/data


