# Generated by Django 3.2 on 2021-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0005_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stages',
            field=models.ManyToManyField(to='ptsapp.Stage'),
        ),
    ]
