# Generated by Django 3.2 on 2021-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0006_application_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='active_status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='sort_order',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
