# Generated by Django 3.2 on 2021-10-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsapp', '0008_alter_stage_stage_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=252)),
                ('internal_identification', models.CharField(blank=True, default='', max_length=252)),
                ('data_approximated', models.BooleanField()),
                ('gear_quality', models.IntegerField(blank=True, null=True)),
                ('gear_supplier', models.CharField(blank=True, default='', max_length=252)),
                ('number_of_teeth', models.IntegerField(blank=True, null=True)),
                ('gear_type', models.CharField(blank=True, default='', max_length=252)),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('normal_pressure_angle_deg', models.IntegerField(blank=True, null=True)),
                ('gear_pitch_dia_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('face_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('gear_tip_dia_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('root_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('assembled_to', models.CharField(blank=True, default='', max_length=252)),
                ('assembled_type', models.CharField(blank=True, default='', max_length=252)),
                ('tooth_thickness_tolerance', models.CharField(blank=True, default='', max_length=252)),
                ('tangential_force_n', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('contact_stress_mpa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('root_stress_mpa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('transverse_contact_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('total_contact_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('profile_crowning', models.IntegerField(blank=True, null=True)),
                ('lead_crowning', models.IntegerField(blank=True, null=True)),
                ('profile_angle_deviation_μm', models.IntegerField(blank=True, null=True)),
                ('cumulative_pitch_error_μm', models.CharField(blank=True, default='', max_length=252)),
                ('total_composite_action_tolerance_μm', models.CharField(blank=True, default='', max_length=252)),
                ('profile_form_deviation_μm', models.CharField(blank=True, default='', max_length=252)),
                ('helix_slope_deviation_μm', models.CharField(blank=True, default='', max_length=252)),
                ('powder_metal', models.BooleanField()),
                ('soft_machining', models.BooleanField()),
                ('heat_treatment', models.BooleanField()),
                ('sizing', models.CharField(blank=True, default='', max_length=252)),
                ('densification', models.BooleanField()),
                ('hard_finishing', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(blank=True, default=50, null=True)),
                ('active_status', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='stages',
            field=models.ManyToManyField(to='ptsapp.Gear'),
        ),
    ]
