version: "3.8"

networks:
  sister:
    name: sister

# volumes:
#   mysqldata:

services:

  djbldr:
    # 172.27.0.30:62xx
    # https://djbuilder17.198.144.183.160.nip.io
    image: nginx:1.25-alpine-slim
    # ports:
    #   - "16220:80"
    expose:
      - "80"
    volumes:
      - ./docker/nginx/nginxmain.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    restart: always
    # not done.. command:       - firebase use production        CMD ["nginx", "-g", "daemon off;"]
    networks:
      - sister
    env_file:
      - ./.env.development.local
    environment:
      # - VIRTUAL_HOST=mark616g.198.144.183.160.nip.io,markg.daveg.win
      # - LETSENCRYPT_HOST=mark616g.198.144.183.160.nip.io,markg.daveg.win
      - VIRTUAL_HOST=djbuilder17.198.144.183.160.nip.io
      - LETSENCRYPT_HOST=djbuilder17.198.144.183.160.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
      - VIRTUAL_NETWORK=sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "9"
