version: "3.6"
#
services:
  #
  php:
    # http://192.168.88.60:6611/exampleapp    
    # http://192.168.88.60:6611/dgnote130    
    restart: unless-stopped
    # image: php:7.3-apache
    build:
      context: ./php
      dockerfile: Dockerfile-php73
    ports:
      - 6611:80
    volumes:
      - ../data/html1:/var/www/html
      - ./php/apache_allow.conf:/etc/apache2/conf-enabled/apache_allow.conf
      # This wipes out the files in the container... - ../data/c-php483b_etc_apache2:/etc/apache2
      # this noworky either..
      # - type: volume
      #   source: etc_apache2
      #   target: /etc/apache2 #/path/in/container
      #   read_only: true
      # - ./data1:/var/www/html
      # - ./apache2.conf:/etc/apache2/apache2.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      #

  dbm:
    image: mysql:8.0
    hostname: pts592db
    restart: always
    env_file:
      - .env
    environment:
      LANG: C.UTF_8 
    # command: --default-authentication-plugin=mysql_native_password
    # https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_file_per_table
    command: --innodb-file-per-table=1 --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "6612:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # folder for mysql's internal data files.
      - ../sysdata/mysqldata:/var/lib/mysql/  
      - ./script:/script
      # folders for imported or exported data, etc.
      - ../sysdata/in-out/:/in-out
      - ../data/crib/:/crib
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    # networks:
    #   - sister2


  adminer:
    # http://10.4.71.231:6613/
    # http://10.4.71.231:7412/  use dbm or ip:port for server while logging in.
    image: adminer:4.7
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    env_file:
      - .env
    ports:
      - 6613:8080
    environment:
      - ADMINER_DEFAULT_SERVER=dbm
      # - ADMINER_PLUGINS='tables-filter tinymce'
    # networks:
    #   - net556


  phpmyadmin:
    # https://github.com/phpmyadmin/docker  
    # http://10.4.71.231:7414/
    # http://192.168.88.60:6614
    image: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
    - 6614:80
    volumes:
    - /sessions
    # - ../phpmyadmin/sessions/:/sessions

# volumes:
#   etc_apache2:

