version: "3.6"
#
networks:
  sister:
    name: sister
  sister2:
    name: sister2

services:
  #
  php:
    # http://192.168.88.60:6611/exampleapp    
    # http://192.168.88.60:6611/dgnote130    
    # http://10.4.1.231:6611/exampleapp    
    # http://10.4.1.231:6611/dgnote130    
    # https://php.198.144.183.160.nip.io/
    
    restart: unless-stopped
    # image: php:7.3-apache
    build:
      context: ./php
      dockerfile: Dockerfile-php73
    ports:
      - 6611:80
    volumes:
      - ../htmldata605o/html01:/var/www/html
      - ./php/apache_allow.conf:/etc/apache2/conf-enabled/apache_allow.conf
      # This wipes out the files in the container... - ../data/c-php483b_etc_apache2:/etc/apache2
      # this noworky either..
      # - type: volume
      #   source: etc_apache2
      #   target: /etc/apache2 #/path/in/container
      #   read_only: true
      # - ./data1:/var/www/html
      # - ./apache2.conf:/etc/apache2/apache2.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - VIRTUAL_HOST=php.198.144.183.160.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=php.198.144.183.160.nip.io
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
    networks:
      - sister


  dbm:
    image: mysql:8.0
    hostname: pts592db
    restart: always
    env_file:
      - .env
    # environment:
    #   LANG: C.UTF_8 
    # command: --default-authentication-plugin=mysql_native_password
    # https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_file_per_table
    command: --innodb-file-per-table=1 --default-authentication-plugin=mysql_native_password  --secure_file_priv=/crib
             #   --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "6612:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # folder for mysql's internal data files.
      - ../sysdata/mysqldata:/var/lib/mysql/  
      - ./script:/script
      # folders for imported or exported data, etc.
      - ../sysdata/in-out/:/in-out
      - ../data/crib/:/crib
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    #
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    networks:
      - sister
      - sister2


  adminer:
    # http://10.4.1.231:6613/
    # http://10.4.1.231:7412/  use dbm or ip:port for server while logging in.
    # https://198.144.183.160.nip.io/
    # https://admr.198.144.183.160.nip.io/
    image: adminer:4.7
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    env_file:
      - .env
    ports:
      - 6613:8080
    environment:
      - ADMINER_DEFAULT_SERVER=dbm
      # - ADMINER_PLUGINS='tables-filter tinymce'
      - VIRTUAL_HOST=admr.198.144.183.160.nip.io
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=admr.198.144.183.160.nip.io
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
    networks:
      - sister
      - sister2


  pmy:
    # https://github.com/phpmyadmin/docker  
    # http://192.168.88.60:6614
    # http://10.4.1.231:6614
    image: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - VIRTUAL_HOST=pmy.198.144.183.160.nip.io
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=pmy.198.144.183.160.nip.io
    - LETSENCRYPT_EMAIL=dgleba@gmail.com
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
    - 6614:80
    volumes:
    - /sessions
    # - ../phpmyadmin/sessions/:/sessions
    networks:
      - sister


# volumes:
#   etc_apache2:

