# Generated by Django 3.2 on 2021-12-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_application2_vehicle2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle2',
            name='Application2s',
        ),
        migrations.AddField(
            model_name='vehicle2',
            name='application2s',
            field=models.ManyToManyField(to='blogapp.Application2'),
        ),
    ]
