version: "3.7"

networks:
  sister:
    name: sister

# volumes:
#   mysqldata:

services:

  vv:
    # 172.27.0.30:62xx
    # image: node:16-alpine
    user: "1000:33"
    working_dir:  /pwa02
    build: .
    # ports:
    #   - "16220:80"
    expose:
      - "80"
    volumes:
      # - ./docker/nginx_616g/nginxmain.conf:/etc/nginx/nginx.conf
      # - ./docker/nginx_616g/default.conf:/etc/nginx/conf.d/default.conf
      - ./pwa02:/pwa02
    restart: always
    networks:
      - sister
    environment:
      -     VIRTUAL_HOST=vpwa01dev.198.144.183.160.nip.io
      - LETSENCRYPT_HOST=vpwa01dev.198.144.183.160.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
      - VIRTUAL_NETWORK=sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "9"



  prod:
    # 172.27.0.30:62xx
    image: nginx:1.21-alpine
    # ports:
    #   - "16220:80"
    expose:
      - "80"
    volumes:
      - ./docker/nginx_616g/nginxmain.conf:/etc/nginx/nginx.conf
      - ./docker/nginx_616g/default.conf:/etc/nginx/conf.d/default.conf
      - ./pwa02/dist:/usr/share/nginx/html
    restart: always
    networks:
      - sister
    environment:
      -     VIRTUAL_HOST=vpwa01.198.144.183.160.nip.io
      - LETSENCRYPT_HOST=vpwa01.198.144.183.160.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
      - VIRTUAL_NETWORK=sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "9"
