version: "3.7"

networks:
  sister2:
    name: sister2

services:

  copy_me_dg:
    # to test this jwilder/LE
    # http://web-108-168-7-24.nip.io/
    # https://web.198.144.183.160.nip.io/
    image: nginx:1.21-alpine
    volumes:
      - ./site:/usr/share/nginx/html
    expose:
      - "80"
    # environment:
      # - VIRTUAL_HOST=davegg.com,198.144.183.160.nip.io,d.davegg.com
      # - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=davegg.com,198.144.183.160.nip.io,d.davegg.com
      #- LETSENCRYPT_HOST=web.c617eef4.nip.io
      # - LETSENCRYPT_EMAIL=dgleba@gmail.com
    restart: always
    networks:
      - sister2


  dbfr:
    image: mariadb:10.5?
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_filerun_username
      MYSQL_PASSWORD: your_filerun_password
      MYSQL_DATABASE: your_filerun_database
    volumes:
      - /filerun/db:/var/lib/mysql

  fileruna:
    image: filerun/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_filerun_database
      FR_DB_USER: your_filerun_username
      FR_DB_PASS: your_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - dbfr
    links:
      - dbfr:dbfr
    ports:
      - "80:80"
    volumes:
      - ./sysdata/filerun-html:/var/www/html
      - ./sysdata/filerun-user-files:/user-files


